topics_folder="hmeg/topics"
# vocab_file="hmeg/vocabs/minilex.toml"  # Optional: path to a custom vocabulary file in TOML format. Required for the "templates" engine.
vocab_level="B1"  # Optional: CEFR level for vocabulary selection: A1 | A2 | B1 | B2 | C1 | C2. Used by the "ollama" engine.

topic="Have, Don’t have, There is, There isn’t / 있어요, 없어요"
number_exercises=10

# Exercise generation engine settings
#
# Depending on the engine a different set of parameters is required.
# * "templates" -- uses the old exercise generation method based on templates.
#   Can do optional grammar_correction using reranker defined using
#   `grammar_correction` parameter
# * "ollama" -- uses the new exercise generation method based on LLMs.
#   Requires `model` parameter to be set to a valid ollama model.
engine="ollama"  # "ollama" | "templates"
model="gemma3:4b"  # necessary when "ollama" engine is used. Make sure you have the model downloaded for ollama
# grammar_correction="kenlm/en"  # "kenlm/en" | "distilgpt2" | "openai"
