topics_folder="hmeg/miniphrase"
vocab_file="hmeg/vocabs/minilex.toml"

topic="Miniphrase: W, Y"
number_exercises=10


# Exercise generation settings
# engine="ollama"  # "ollama" | "legacy"
# model="ministral-3:14b"  # necessary when "ollama" engine is used. Make sure you have the model downloaded for ollama
# grammar_correction="kenlm/en"  # "kenlm/en" | "distilgpt2" | "openai"
