verbs_singular_3rd = {
    'arrive': 'arrives', 'ask': 'asks',
    'become': 'becomes', 'begin': 'begins', 'believe': 'believes', 'borrow': 'borrows', 'bring': 'brings', 'buy': 'buys',
    'clean': 'cleans', 'come': 'comes', 'continue': 'continues', 'cry': 'cries',
    'damage': 'damages', 'do': 'does', 'drop': 'drops',
    'eat': 'eats',
    'fall': 'falls', 'feel': 'feels', 'find': 'finds', 'finish': 'finishes', 'forget': 'forgets', 'free': 'frees',
    'have': 'has', 'head': 'heads', 'hold': 'holds', 'hope': 'hopes', 'hurt': 'hurts',
    'joke': 'jokes',
    'keep': 'keeps', 'know': 'knows',
    'laugh': 'laughs', 'learn': 'learns', 'leave': 'leaves', 'lend': 'lends', 'let': 'lets', 'lie': 'lies', 'like': 'likes', 'listen': 'listens', 'live': 'lives', 'look': 'looks', 'look for': 'looks for', 'love': 'loves',
    'make': 'makes', 'mean': 'means', 'meet': 'meets',
    'name': 'names', 'need': 'needs',
    'pay': 'pays', 'place': 'places', 'play': 'plays', 'put': 'puts',
    'read': 'reads', 'remember': 'remembers',
    'say': 'says', 'see': 'sees', 'sell': 'sells', 'send': 'sends', 'show': 'shows', 'shut': 'shuts', 'sing': 'sings', 'speak': 'speaks', 'stand': 'stands', 'stay': 'stays', 'stop': 'stops', 'suggest': 'suggests',
    'take': 'takes', 'talk': 'talks', 'teach': 'teaches', 'think': 'thinks', 'travel': 'travels',
    'understand': 'understands', 'use': 'uses',
    'wait': 'waits', 'walk': 'walks', 'want': 'wants', 'work': 'works', 'worry': 'worries', 'write': 'writes'
}
