name="Past Tense / -았/었/였어요 (했어요)"
levels=[
    {resource_name="TTMIK", level=1}
]
links=[]
exercises=[
    """
    S -> P V
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it'
    V -> '{verb:past}'
    """
]
