name="While / -(으)면서"
levels=[
    {resource_name="TTMIK", level=9},
    {resource_name="King Sejong Institute Practical Korean", level=3}
]
links=[]
exercises=[
    """
    S -> P V 'and' V
    P -> 'I' | 'they' | 'you' | 'we' |
    V -> '{verb}'
    """,
    """
    S -> P V 'and' V
    P -> 'he' | 'she' | 'it' |
    V -> '{verb:3s}'
    """
]
