name="From A To B, From C Until D / -에서/부터 -까지"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-9-16/lesson-12/#kp4"
]
exercises=[
    """
    S -> 'From' T 'to' T
    T -> '{noun}' | '{weekday}' | '{season}'
    """,
    """
    S -> 'From' T 'until' T
    T -> '{weekday}' | '{season}'
    """,
    """
    S -> P 'will wait until {number:100}:00'
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> P 'will go from {place} to {place}'
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> P 'will be at {place} from {number:100}:00'
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it'
    """
]
