name="I want to… / -고 싶어요"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 1"},
    {resource_name="King Sejong Institute Practical Korean", level="1. Beginner"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-17/#co5"
]
exercises=[
    """
    S -> P 'want to' V
    P -> 'I' | 'they' | 'you' | 'we'
    V -> '{verb}'
    """,
    """
    S -> P 'wants to' V
    P -> 'he' | 'she' | 'it'
    V -> '{verb}'
    """
]
