name="Negative Sentences / 안, -지 않다"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 1"},
    {resource_name="King Sejong Institute Practical Korean", level="1. Beginner"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
    {resource_name="Oh, my Korean!", level="1A"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-1-8/unit-1-lesson-8/#negsent"
]
exercises=[
    """
    S -> P 'don`t' V
    P -> 'I' | 'they' | 'you' | 'we' |
    V -> '{verb}'
    """,
    """
    S -> P 'doesn`t' V
    P -> 'he' | 'she' | 'it'
    V -> '{verb}'
    """,
    """
    S -> P 'didn`t' V
    P -> 'I' | 'they' | 'you' | 'we' | 'he' | 'she' | 'it' |
    V -> '{verb}'
    """
]
