name="And, with / -하고, -(이)랑"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-9-16/lesson-13/#kp1"
]
exercises=[
    """
    S -> '{noun} and {noun}'
    """,
    """
    S -> P 'see {noun} and {noun}'
    P -> 'I' | 'You' | 'They' | 'We'
    """,
    """
    S -> P 'sees {noun} and {noun}'
    P -> 'He' | 'She' | 'It'
    """,
    """
    S -> P 'bought {noun} and {noun}'
    P -> 'I' | 'You' | 'They' | 'We' | 'He' | 'She' | 'It'
    """,
]
