name="Particles For Method, Way / -(으)로"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-9-16/lesson-12/#kp5",
]
exercises=[
    """
    S -> A V
    A -> '{adverb}'
    V -> '{verb}'
    """
]
