name="Present Progressive / -고 있어요"
levels=[
    {resource_name="TTMIK", level="Level 2"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-18/#ppt"
]
exercises=[
    """
    S -> P V
    P -> 'I am' | 'they are' | 'you are' | 'we are' | 'he is' | 'she is' | 'it is' |
    V -> '{verb:ing}'
    """
]
