name="Before -ing / -기 전에"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 1"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-24/#242",
    "https://www.topikguide.com/verb-%EA%B8%B0-%EC%A0%84%EC%97%90-and-noun-%EC%A0%84%EC%97%90-korean-grammar/",
]
exercises=[
    """
    S -> 'Before {verb:ing} {verb}'
    """
]
