name="But still, Nevertheless / 그래도"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-48/#new",
]
exercises=[
    """
    S -> '{noun} is {adj} but {adj}'
    """
]
