name="Linking Verbs with -고"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-17/#co"
]
exercises=[
    """
    S -> '{verb} and {verb}'
    """,
    """
    S -> '{verb} and {verb} and {verb}'
    """
]
