name="Linking Verbs with -는데 / noun + -인데, adjective + -ㄴ데"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 4"},
    {resource_name="King Sejong Institute Practical Korean", level="2. Beginner"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
    {resource_name="Oh, my Korean!", level="1B"},
    {resource_name="Oh, my Korean!", level="2A"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-76-83/lesson-76/#763"
]
exercises=[
    """
    S -> '{verb} but {verb}' | '{verb} and {verb}'
    """,
    """
    S -> '{noun} but {adj}'
    """,
]
