name="To look like, To seem like / 같아요"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-34-41/lesson-35/#351"
]
exercises=[
    """
    S -> '{noun} looks like {noun}' | '{noun} seems like {noun}'
    """
]
