name="Well then, In that case, If so / 그러면, 그럼"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-43/#431"
]
exercises=[
    """
    S -> C P '{verb}'
    C -> 'well then' | 'in that case' | 'if so'
    P -> 'I' | 'you' | 'we' | 'they'
    """,
    """
    S -> C P '{verb:3s}'
    C -> 'well then' | 'in that case' | 'if so'
    P -> 'he' | 'she' | 'it'
    """,
    """
    S -> 'If so' P 'not {verb:ing}'
    P -> 'I am' | 'you are' | 'we are' | 'they are' | 'he is' | 'she is' | 'it is'
    """,
]
