name="Do you want to …? / -(으)ㄹ래요?"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 2"},
    {resource_name="King Sejong Institute Practical Korean", level="2. Beginner"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
    {resource_name="Oh, my Korean!", level="2B"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-44/#442"
]
exercises=[
    """
    S -> 'Do you want to {verb}?'
    """,
]
