name="The more … the more … / -(으)면 -(으)ㄹ수록"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 6"},
]
links=[
    "https://www.howtostudykorean.com/unit-6/lessons-126-133/lesson-132/#1321"
]
exercises=[
    """
    S -> 'The more' P '{verb} the more' P 'get {adj}'
    P -> 'I' | 'you' | 'we' | 'they'
    """,
    """
    S -> 'The more' P '{verb:3s} the more' P 'gets {adj}'
    P -> 'he' | 'she' | 'it'
    """
]
