name="To try doing something / -아/어/여 보다, 해 보다"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-26-33/lesson-32/#323"
]
exercises=[
    """
    S -> 'Try {verb:ing}.'
    """,
    """
    S -> P 'tries {verb:ing}.'
    P -> 'he' | 'she' | 'it'
    """,
    """
    S -> P 'try {verb:ing}.'
    P -> 'I' | 'You' | 'They' | 'We'
    """,
    """
    S -> P 'tried {verb:ing}.'
    P -> 'I' | 'You' | 'They' | 'We' | 'He' | 'She' | 'It'
    """,
]
