name="To become + adjective / -아/어/여지다"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 1"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-17-25-2/lesson-18/#a"
]
exercises=[
    """
    S -> '{noun} became {adj}.'
    """,
    """
    S -> '{noun} will become {adj}.'
    """,
]
