name="Verb ending -지요/-죠"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 4"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-92-100/lesson-93/#931"
]
exercises=[
    """
    S -> 'That’s true, {verb:ing} is {adj}.'
    """,
    """
    S -> '{noun} was {adj}, right?' | '{noun} is {adj}, right?'
    """
]
