name="Verb ending -지요/-죠"
levels=[
    {resource_name="TTMIK", level=4}
]
links=[]
exercises=[
    """
    S -> 'That’s true, {verb:ing} is {adj}.'
    """,
    """
    S -> '{noun} was {adj}, right?' | '{noun} is {adj}, right?'
    """
]
