name="You shouldn’t…, You’re not supposed to… / -(으)면 안 돼요, 하면 안 돼요"
levels=[
    {resource_name="TTMIK", level="Level 4"},
    {resource_name="HTSK", level="Unit 4"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-76-83/lesson-80/#802"
]
exercises=[
    """
    S -> P 'should not {verb}.'
    P -> 'he' | 'she' | 'it' | 'I' | 'you' | 'they' | 'we'
    """,
    """
    S -> P 'not supposed to {verb}.'
    P -> 'he is' | 'she is' | 'it is' | 'I am' | 'you are' | 'they are' | 'we are'
    """,
]
