name="As soon as … / -자마자"
levels=[
    {resource_name="TTMIK", level="Level 5"},
    {resource_name="HTSK", level="Unit 4"},
    {resource_name="King Sejong Institute Practical Korean", level="4. Intermediate"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-84-91/lesson-84/#841"
]
exercises=[
    """
    S -> 'As soon as' P '{verb:past}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> 'As soon as' P 'will {verb}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """
]
