name="It is about to …, I am planning to … / -(으)려고 하다"
levels=[
    {resource_name="TTMIK", level="Level 5"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-26-33/lesson-32/#321"
]
exercises=[
    """
    S -> P 'planning to {verb}.'
    P -> 'I am' | 'you are' | 'they are' | 'we are' | 'he is' | 'she is' | 'it is'
    """,
    """
    S -> P 'planned to {verb}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
]
