name="Since, Because, As / -(으)니까"
levels=[
    {resource_name="TTMIK", level="Level 5"},
    {resource_name="HTSK", level="Unit 4"},
    {resource_name="King Sejong Institute Practical Korean", level="2. Beginner"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
    {resource_name="Oh, my Korean!", level="1B"},
    {resource_name="Oh, my Korean!", level="2A"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-76-83/lesson-81/#811"
]
exercises=[
    """
    S -> P L 'it because it is {adj}.'
    L -> 'like' | 'don`t like'
    P -> 'I' | 'you' | 'they' | 'we'
    """,
    """
    S -> P L 'it because it is {adj}.'
    L -> 'likes' | 'doesn`t like'
    P -> 'he' | 'she' | 'it'
    """,
    """
    S -> 'I could not do it, because it was {adj}.'
    """,
]
