name="(To say) that something/someone is + noun / 명사 + -(이)라고 (말하다)"
levels=[
    {resource_name="TTMIK", level="Level 5"},
    {resource_name="HTSK", level="Unit 3"},
]
links=[
    "https://www.howtostudykorean.com/unit-3-intermediate-korean-grammar/unit-3-lessons-51-58/lesson-52/#523"
]
exercises=[
    """
    S -> P 'said it was {noun}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
]
