name="(To say) that something/someone + verb / 동사 + -(ㄴ/는)다고 (말하다)"
levels=[
    {resource_name="TTMIK", level="Level 5"},
    {resource_name="HTSK", level="Unit 3"},
]
links=[
    "https://www.howtostudykorean.com/unit-3-intermediate-korean-grammar/unit-3-lessons-51-58/lesson-52/#523"
]
exercises=[
    """
    S -> P 'said' P '{verb:past}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> P 'said' P 'would {verb}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> P 'said' P 'did not {verb}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> P 'said' P 'would not {verb}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
    """
    S -> P 'said it was {adj}.'
    P -> 'I' | 'you' | 'they' | 'we' | 'he' | 'she' | 'it'
    """,
]
