name="Do you mind if I …? / -아/어/여도 돼요?"
levels=[
    {resource_name="TTMIK", level="Level 6"},
    {resource_name="HTSK", level="Unit 2"},
]
links=[
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-49/"
]
exercises=[
    """
    S -> 'Do you mind if I {verb}?'
    """,
]
