name="I thought I would …, I didn’t think you would … / -(으)ㄴ/ㄹ 줄 알다"
levels=[
    {resource_name="TTMIK", level="Level 6"},
    {resource_name="HTSK", level="Unit 4"},
]
links=[
    "https://www.howtostudykorean.com/upper-intermediate-korean-grammar/unit-4-lessons-84-91/lesson-85/#851"
]
exercises=[
    """
    S -> 'I thought {person} would {verb}'
    """,
    """
    S -> 'I did not think {person} would {verb}'
    """,
]
