name="I DID do it, I DO like it / -기는 하다"
levels=[
    {resource_name="TTMIK", level="Level 6"},
    {resource_name="HTSK", level="Unit 5"},
    {resource_name="King Sejong Institute Practical Korean", level="3. Intermediate"},
    {resource_name="Oh, my Korean!", level="2A"},
]
links=[
    "https://mykoreanramblings.com/however/",
    "https://www.howtostudykorean.com/unit-5/lessons-101-108/lesson-104/#1043",
    "http://ohmykorean.com/?p=376"
]
exercises=[
    """
    S -> '{person} actually did {verb}, but ...'
    """,
    """
    S -> '{noun:nonperson} actually was {adj}, but ...'
    """,
]
