name="Suffix -겠-"
levels=[
    {resource_name="TTMIK", level="Level 6"},
    {resource_name="HTSK", level="Unit 2"},
    {resource_name="HTSK", level="Unit 3"},
]
links=[
    "https://www.topikguide.com/%EA%B2%A0-korean-grammar/",
    "https://www.howtostudykorean.com/unit-2-lower-intermediate-korean-grammar/unit-2-lessons-42-50/lesson-46/#461",
    "https://www.howtostudykorean.com/unit-3-intermediate-korean-grammar/unit-3-lessons-59-66/lesson-61/#613"
]
exercises=[
    """
    S -> 'As promised {person} will {verb}.'
    """,
    """
    S -> '{person} thinks {noun:nonperson} will be {adj}.'
    """,
    """
    S -> '{person} intends to become more {adj}.'
    """,
]
