name="While / -(으)면서"
levels=[
    {resource_name="TTMIK", level="Level 9"},
    {resource_name="King Sejong Institute Practical Korean", level="3. Intermediate"},
    {resource_name="HTSK", level="Unit 3"},
]
links=[
    "https://www.howtostudykorean.com/unit-3-intermediate-korean-grammar/unit-3-lessons-59-66/lesson-62/#621"
]
exercises=[
    """
    S -> P V 'and' V
    P -> 'I' | 'they' | 'you' | 'we' |
    V -> '{verb}'
    """,
    """
    S -> P V 'and' V
    P -> 'he' | 'she' | 'it' |
    V -> '{verb:3s}'
    """
]
