name="Age"
levels=[
    {resource_name="TTMIK", level="Level 1"},
    {resource_name="HTSK", level="Unit 1"},
    {resource_name="King Sejong Institute Practical Korean", level="1. Beginner"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
    {resource_name="Oh, my Korean!", level="1A"},
]
links=[
    "https://www.howtostudykorean.com/unit1/unit-1-lessons-9-16/unit-1-lesson-10/#age"
]
exercises=[
    """
    S -> P '{number:100} years old'
    P -> 'I am' | '{person} is'
    """
]
