name="Large numbers"
levels=[
    {resource_name="TTMIK", level="Level 3"},
    {resource_name="HTSK", level="Unit 6"},
    {resource_name="King Sejong Institute Practical Korean", level="1. Beginner"},
    {resource_name="Korean Grammar in Use", level="Beginning"},
]
links=[
    "https://www.howtostudykorean.com/unit-6/lessons-126-133/lesson130/#1301"
]
exercises=[
    """
    S -> '{number:large}'
    """,
    """
    S -> 'The price is {number:large} won'
    """,
    """
    S -> '{number:large} won was transfered.'
    """,
    """
    S -> 'Received {number:large} won.'
    """,
]
