name: Unit-tests
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install packages
      - run: pip install -r requirements.txt
      - run: pip install pytest
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: pytest test
